import { FormEvent, useEffect, useState } from "react";

const apiUrl=import.meta.env.VITE_API_URL??"http://localhost:4000";
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${apiUrl}${path}`,{credentials:"include",headers:{...(init?.body?{"Content-Type":"application/json"}:{}),...(init?.headers??{})},...init});const payload=await response.json().catch(()=>({})) as T&{error?:string};if(!response.ok)throw new Error(payload.error??"request_failed");return payload;}
const money=(value:unknown)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value??0));
type Overview={tiss:{total:number;amount:string;pending:number};denials:{total:number;denied:string;recovered:string;open:number};fiscal:{total:number;authorized:string;pending:number};reconciliation:{matched:number;unmatched:number};migrations:{total:number;completed:number;failed:number};stock:{total:number;low_stock:number;stock_value:string};ai:{total:number;awaiting_review:number};telehealth:{total:number;active:number};integrations:{medplum:boolean;nfse:string;bank:string;ai:string}};
type Operator={id:string;name:string;ans_registry:string;tiss_version:string};
type Guide={id:string;guide_number:string;guide_type:string;operator_name:string;patient_name:string|null;total_amount:string;risk_score:number;status:string};
type Denial={id:string;guide_number:string;operator_name:string;reason_code:string;reason_description:string;denied_amount:string;appeal_deadline:string|null;status:string};
type Invoice={id:string;patient_name:string|null;kind:string;provider:string;amount:string;status:string;invoice_number:string|null;verification_code:string|null};
type Statement={id:string;occurred_on:string;description:string;amount:string;status:string;filename:string};
type Migration={id:string;source:string;filename:string;status:string;totals:Record<string,number>;errors:Array<unknown>};
type Stock={id:string;name:string;sku:string;unit:string;current_quantity:string;minimum_quantity:string;average_cost:string};
type AiJob={id:string;kind:string;status:string;created_at:string};
type Telehealth={id:string;patient_name:string;starts_at:string;room_key:string;status:string};
type MedplumStatus={configured:boolean;connected:boolean;baseUrl:string;error?:string};
type FhirSync={summary:{pending:number;processing:number;completed:number;failed:number};items:Array<{local_resource_type:string;local_resource_id:string;status:string;attempts:number;last_error?:string;last_synced_at?:string;updated_at:string}>};
type Patient={id:string;full_name:string};
type Appointment={id:string;patient_name:string;starts_at:string};

const tabs=["Cockpit","TISS","Glosas","NFSe","Conciliação","Migração","Estoque","IA e teleconsulta","Medplum"] as const;
type Tab=typeof tabs[number];

export function EnterpriseSuite({patients,appointments}:{patients:Patient[];appointments:Appointment[]}){
 const[tab,setTab]=useState<Tab>("Cockpit");const[overview,setOverview]=useState<Overview|null>(null);const[operators,setOperators]=useState<Operator[]>([]);const[guides,setGuides]=useState<Guide[]>([]);const[denials,setDenials]=useState<Denial[]>([]);const[invoices,setInvoices]=useState<Invoice[]>([]);const[statements,setStatements]=useState<Statement[]>([]);const[migrations,setMigrations]=useState<Migration[]>([]);const[stock,setStock]=useState<Stock[]>([]);const[aiJobs,setAiJobs]=useState<AiJob[]>([]);const[telehealth,setTelehealth]=useState<Telehealth[]>([]);const[medplum,setMedplum]=useState<MedplumStatus|null>(null);const[fhirSync,setFhirSync]=useState<FhirSync|null>(null);const[error,setError]=useState("");const[message,setMessage]=useState("");
 const[operatorForm,setOperatorForm]=useState({name:"",ansRegistry:"",tissVersion:"4.01.00",appealDeadlineDays:30});const[guideForm,setGuideForm]=useState({operatorId:"",patientId:"",guideType:"consultation",guideNumber:"",beneficiaryNumber:"",authorizationNumber:"",totalAmount:""});const[denialForm,setDenialForm]=useState({guideId:"",reasonCode:"",reasonDescription:"",deniedAmount:"",category:"administrative",appealDeadline:""});const[invoiceForm,setInvoiceForm]=useState({patientId:"",kind:"service",amount:""});const[stockForm,setStockForm]=useState({name:"",sku:"",unit:"un",minimumQuantity:"0",averageCost:"0"});const[aiForm,setAiForm]=useState({patientId:"",kind:"summary"});const[teleForm,setTeleForm]=useState({appointmentId:"",roomKey:"",recordingEnabled:false,paymentRequired:false});
 const load=async()=>{try{const[o,op,g,d,f,s,m,i,a,t,mp,sync]=await Promise.all([api<Overview>("/v1/advanced/overview"),api<{items:Operator[]}>("/v1/advanced/tiss/operators"),api<{items:Guide[]}>("/v1/advanced/tiss/guides"),api<{items:Denial[]}>("/v1/advanced/tiss/denials"),api<{items:Invoice[]}>("/v1/advanced/fiscal"),api<{items:Statement[]}>("/v1/advanced/reconciliation"),api<{items:Migration[]}>("/v1/advanced/migrations"),api<{items:Stock[]}>("/v1/advanced/inventory"),api<{items:AiJob[]}>("/v1/advanced/ai"),api<{items:Telehealth[]}>("/v1/advanced/telehealth"),api<MedplumStatus>("/v2/medplum/status"),api<FhirSync>("/v2/medplum/sync")]);setOverview(o);setOperators(op.items);setGuides(g.items);setDenials(d.items);setInvoices(f.items);setStatements(s.items);setMigrations(m.items);setStock(i.items);setAiJobs(a.items);setTelehealth(t.items);setMedplum(mp);setFhirSync(sync);setError("");}catch(caught){setError(caught instanceof Error?caught.message:"Falha ao carregar módulos avançados.");}};useEffect(()=>{void load();},[]);
 const run=async(action:()=>Promise<unknown>,success:string)=>{try{await action();setMessage(success);setError("");await load();}catch(caught){setError(caught instanceof Error?caught.message:"Operação não concluída.");}};
 const submitOperator=(event:FormEvent)=>{event.preventDefault();void run(()=>api("/v1/advanced/tiss/operators",{method:"POST",body:JSON.stringify(operatorForm)}),"Operadora cadastrada.");};
 const submitGuide=(event:FormEvent)=>{event.preventDefault();void run(()=>api("/v1/advanced/tiss/guides",{method:"POST",body:JSON.stringify({...guideForm,patientId:guideForm.patientId||undefined,beneficiaryNumber:guideForm.beneficiaryNumber||undefined,authorizationNumber:guideForm.authorizationNumber||undefined,totalAmount:Number(guideForm.totalAmount),items:[]})}),"Guia criada e validada.");};
 const submitDenial=(event:FormEvent)=>{event.preventDefault();void run(()=>api("/v1/advanced/tiss/denials",{method:"POST",body:JSON.stringify({...denialForm,deniedAmount:Number(denialForm.deniedAmount),appealDeadline:denialForm.appealDeadline||undefined})}),"Glosa registrada no cockpit.");};
 const submitInvoice=(event:FormEvent)=>{event.preventDefault();void run(()=>api("/v1/advanced/fiscal",{method:"POST",body:JSON.stringify({...invoiceForm,patientId:invoiceForm.patientId||undefined,amount:Number(invoiceForm.amount)})}),"Documento fiscal processado.");};
 const importOfx=async(file:File)=>run(()=>file.text().then(content=>api("/v1/advanced/reconciliation/ofx",{method:"POST",body:JSON.stringify({filename:file.name,content})})),"Extrato OFX importado.");
 const importCsv=async(file:File,source:string)=>{let jobId="";await run(async()=>{const created=await api<{id:string}>("/v1/advanced/migrations",{method:"POST",body:JSON.stringify({source,filename:file.name})});jobId=created.id;const csv=await file.text();return api(`/v1/advanced/migrations/${jobId}/run`,{method:"POST",body:JSON.stringify({csv,dryRun:false})});},"Migração concluída e auditada.");};
 const submitStock=(event:FormEvent)=>{event.preventDefault();void run(()=>api("/v1/advanced/inventory",{method:"POST",body:JSON.stringify({...stockForm,minimumQuantity:Number(stockForm.minimumQuantity),averageCost:Number(stockForm.averageCost)})}),"Item de estoque cadastrado.");};
 const submitAi=(event:FormEvent)=>{event.preventDefault();void run(()=>api("/v1/advanced/ai",{method:"POST",body:JSON.stringify({kind:aiForm.kind,patientId:aiForm.patientId||undefined,inputReference:{origin:"manual"}})}),"Tarefa de IA criada com revisão humana obrigatória.");};
 const submitTele=(event:FormEvent)=>{event.preventDefault();void run(()=>api("/v1/advanced/telehealth",{method:"POST",body:JSON.stringify(teleForm)}),"Sala de teleconsulta criada.");};
 return <div className="enterprise-suite"><div className="module-tabs">{tabs.map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</div>{message&&<div className="form-message success">{message}</div>}{error&&<div className="form-message error banner">{error}</div>}
 {tab==="Cockpit"&&overview&&<><section className="enterprise-kpis"><article><span>Faturamento TISS</span><b>{money(overview.tiss.amount)}</b><small>{overview.tiss.pending} pendentes</small></article><article><span>Valor glosado</span><b>{money(overview.denials.denied)}</b><small>{money(overview.denials.recovered)} recuperado</small></article><article><span>NFSe autorizada</span><b>{money(overview.fiscal.authorized)}</b><small>{overview.fiscal.pending} em processamento</small></article><article><span>Conciliação</span><b>{overview.reconciliation.matched}</b><small>{overview.reconciliation.unmatched} sem conciliar</small></article><article><span>Estoque</span><b>{money(overview.stock.stock_value)}</b><small>{overview.stock.low_stock} itens baixos</small></article><article><span>Migrações</span><b>{overview.migrations.completed}</b><small>{overview.migrations.failed} falharam</small></article></section><section className="panel integration-grid"><div><span className="eyebrow">Fundação clínica</span><h2>Medplum FHIR</h2><p>{overview.integrations.medplum?"Credenciais configuradas":"Aguardando Client ID e secret"}</p></div><div><span className="eyebrow">Fiscal</span><h2>NFSe</h2><p>Modo {overview.integrations.nfse}</p></div><div><span className="eyebrow">Conciliação</span><h2>Banco</h2><p>{overview.integrations.bank}</p></div><div><span className="eyebrow">Inteligência clínica</span><h2>IA</h2><p>Modo {overview.integrations.ai}</p></div></section></>}
 {tab==="TISS"&&<div className="enterprise-columns"><form className="panel enterprise-form" onSubmit={submitOperator}><span className="eyebrow">Convênios</span><h2>Nova operadora</h2><label>Nome<input required value={operatorForm.name} onChange={e=>setOperatorForm({...operatorForm,name:e.target.value})}/></label><label>Registro ANS<input required value={operatorForm.ansRegistry} onChange={e=>setOperatorForm({...operatorForm,ansRegistry:e.target.value})}/></label><label>Versão TISS<input value={operatorForm.tissVersion} onChange={e=>setOperatorForm({...operatorForm,tissVersion:e.target.value})}/></label><button className="primary-button compact">Cadastrar operadora</button></form><form className="panel enterprise-form" onSubmit={submitGuide}><span className="eyebrow">Faturamento</span><h2>Nova guia TISS</h2><label>Operadora<select required value={guideForm.operatorId} onChange={e=>setGuideForm({...guideForm,operatorId:e.target.value})}><option value="">Selecione</option>{operators.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Paciente<select value={guideForm.patientId} onChange={e=>setGuideForm({...guideForm,patientId:e.target.value})}><option value="">Opcional</option>{patients.map(item=><option key={item.id} value={item.id}>{item.full_name}</option>)}</select></label><label>Número da guia<input required value={guideForm.guideNumber} onChange={e=>setGuideForm({...guideForm,guideNumber:e.target.value})}/></label><label>Carteirinha<input value={guideForm.beneficiaryNumber} onChange={e=>setGuideForm({...guideForm,beneficiaryNumber:e.target.value})}/></label><label>Valor<input required type="number" min="0" step="0.01" value={guideForm.totalAmount} onChange={e=>setGuideForm({...guideForm,totalAmount:e.target.value})}/></label><button className="primary-button compact">Validar e criar guia</button></form><section className="panel enterprise-list wide"><div className="panel-head"><h2>Guias</h2><span>{guides.length} registro(s)</span></div>{guides.map(item=><div className="enterprise-row" key={item.id}><b>{item.guide_number}</b><span>{item.operator_name}</span><span>{item.patient_name??"Sem paciente"}</span><span>{money(item.total_amount)}</span><span className="status waiting">Risco {item.risk_score}</span><span>{item.status}</span></div>)}</section></div>}
 {tab==="Glosas"&&<div className="enterprise-columns"><form className="panel enterprise-form" onSubmit={submitDenial}><span className="eyebrow">Prevenir · recuperar · aprender</span><h2>Registrar glosa</h2><label>Guia<select required value={denialForm.guideId} onChange={e=>setDenialForm({...denialForm,guideId:e.target.value})}><option value="">Selecione</option>{guides.map(item=><option key={item.id} value={item.id}>{item.guide_number} · {item.operator_name}</option>)}</select></label><label>Código do motivo<input required value={denialForm.reasonCode} onChange={e=>setDenialForm({...denialForm,reasonCode:e.target.value})}/></label><label>Motivo<textarea required value={denialForm.reasonDescription} onChange={e=>setDenialForm({...denialForm,reasonDescription:e.target.value})}/></label><label>Valor glosado<input required type="number" min="0.01" step="0.01" value={denialForm.deniedAmount} onChange={e=>setDenialForm({...denialForm,deniedAmount:e.target.value})}/></label><label>Prazo de recurso<input type="date" value={denialForm.appealDeadline} onChange={e=>setDenialForm({...denialForm,appealDeadline:e.target.value})}/></label><button className="primary-button compact">Adicionar ao cockpit</button></form><section className="panel enterprise-list"><div className="panel-head"><h2>Cockpit de glosas</h2><span>{denials.length} item(ns)</span></div>{denials.map(item=><div className="enterprise-row denial" key={item.id}><b>{item.guide_number}</b><span>{item.reason_code} · {item.reason_description}</span><strong>{money(item.denied_amount)}</strong><span>{item.appeal_deadline??"Sem prazo"}</span><span className="status waiting">{item.status}</span></div>)}</section></div>}
 {tab==="NFSe"&&<div className="enterprise-columns"><form className="panel enterprise-form" onSubmit={submitInvoice}><span className="eyebrow">Fiscal</span><h2>Emitir documento</h2><label>Paciente<select value={invoiceForm.patientId} onChange={e=>setInvoiceForm({...invoiceForm,patientId:e.target.value})}><option value="">Sem vínculo</option>{patients.map(item=><option key={item.id} value={item.id}>{item.full_name}</option>)}</select></label><label>Tipo<select value={invoiceForm.kind} onChange={e=>setInvoiceForm({...invoiceForm,kind:e.target.value})}><option value="service">Serviço</option><option value="product">Produto</option></select></label><label>Valor<input required type="number" min="0.01" step="0.01" value={invoiceForm.amount} onChange={e=>setInvoiceForm({...invoiceForm,amount:e.target.value})}/></label><button className="primary-button compact">Emitir NFSe</button></form><section className="panel enterprise-list"><div className="panel-head"><h2>Documentos fiscais</h2><span>{invoices.length}</span></div>{invoices.map(item=><div className="enterprise-row" key={item.id}><b>{item.invoice_number??"Aguardando"}</b><span>{item.patient_name??"Sem paciente"}</span><span>{money(item.amount)}</span><span>{item.provider}</span><span className="status completed">{item.status}</span></div>)}</section></div>}
 {tab==="Conciliação"&&<div className="enterprise-columns"><section className="panel enterprise-form"><span className="eyebrow">OFX</span><h2>Importar extrato bancário</h2><p>O arquivo é interpretado localmente e cada movimentação entra na fila de conciliação.</p><label className="file-field">Escolher OFX<input type="file" accept=".ofx,text/plain" onChange={e=>{const file=e.target.files?.[0];if(file)void importOfx(file);}}/></label></section><section className="panel enterprise-list"><div className="panel-head"><h2>Movimentações</h2><span>{statements.length}</span></div>{statements.map(item=><div className="enterprise-row" key={item.id}><b>{item.occurred_on}</b><span>{item.description}</span><strong className={Number(item.amount)>=0?"positive":"negative"}>{money(item.amount)}</strong><span>{item.filename}</span><span className="status waiting">{item.status}</span></div>)}</section></div>}
 {tab==="Migração"&&<div className="enterprise-columns"><section className="panel enterprise-form"><span className="eyebrow">Importadores</span><h2>Migrar concorrente</h2><p>CSV com colunas como nome, data de nascimento, telefone e e-mail. A operação registra contagem e erros.</p>{["iclinic","feegow","amplimed","prodoctor","csv"].map(source=><label className="file-field" key={source}>Importar {source}<input type="file" accept=".csv,text/csv" onChange={e=>{const file=e.target.files?.[0];if(file)void importCsv(file,source);}}/></label>)}</section><section className="panel enterprise-list"><div className="panel-head"><h2>Histórico de migrações</h2><span>{migrations.length}</span></div>{migrations.map(item=><div className="enterprise-row" key={item.id}><b>{item.source}</b><span>{item.filename}</span><span>{item.totals?.imported??0} importados</span><span className="status completed">{item.status}</span></div>)}</section></div>}
 {tab==="Estoque"&&<div className="enterprise-columns"><form className="panel enterprise-form" onSubmit={submitStock}><span className="eyebrow">Insumos</span><h2>Novo item</h2><label>Nome<input required value={stockForm.name} onChange={e=>setStockForm({...stockForm,name:e.target.value})}/></label><label>SKU<input required value={stockForm.sku} onChange={e=>setStockForm({...stockForm,sku:e.target.value})}/></label><label>Unidade<input value={stockForm.unit} onChange={e=>setStockForm({...stockForm,unit:e.target.value})}/></label><label>Estoque mínimo<input type="number" min="0" step="0.001" value={stockForm.minimumQuantity} onChange={e=>setStockForm({...stockForm,minimumQuantity:e.target.value})}/></label><label>Custo médio<input type="number" min="0" step="0.01" value={stockForm.averageCost} onChange={e=>setStockForm({...stockForm,averageCost:e.target.value})}/></label><button className="primary-button compact">Cadastrar item</button></form><section className="panel enterprise-list"><div className="panel-head"><h2>Posição de estoque</h2><span>{stock.length}</span></div>{stock.map(item=><div className="enterprise-row" key={item.id}><b>{item.name}</b><span>{item.sku}</span><strong>{item.current_quantity} {item.unit}</strong><span>Mín. {item.minimum_quantity}</span><span>{money(item.average_cost)}</span></div>)}</section></div>}
 {tab==="IA e teleconsulta"&&<div className="enterprise-columns"><form className="panel enterprise-form" onSubmit={submitAi}><span className="eyebrow">Humano no comando</span><h2>Nova tarefa de IA</h2><label>Paciente<select value={aiForm.patientId} onChange={e=>setAiForm({...aiForm,patientId:e.target.value})}><option value="">Sem paciente</option>{patients.map(item=><option key={item.id} value={item.id}>{item.full_name}</option>)}</select></label><label>Função<select value={aiForm.kind} onChange={e=>setAiForm({...aiForm,kind:e.target.value})}><option value="summary">Resumo pré-consulta</option><option value="coding">Sugestão CID/TUSS</option><option value="ambient_note">Escriba ambiente</option><option value="no_show">Risco de falta</option><option value="denial_risk">Risco de glosa</option></select></label><button className="primary-button compact">Criar para revisão</button><p>{aiJobs.length} tarefa(s), sempre sujeitas à aprovação humana.</p></form><form className="panel enterprise-form" onSubmit={submitTele}><span className="eyebrow">LiveKit adapter</span><h2>Nova teleconsulta</h2><label>Agendamento<select required value={teleForm.appointmentId} onChange={e=>setTeleForm({...teleForm,appointmentId:e.target.value})}><option value="">Selecione</option>{appointments.map(item=><option key={item.id} value={item.id}>{item.patient_name} · {new Date(item.starts_at).toLocaleString("pt-BR")}</option>)}</select></label><label>Chave da sala<input required minLength={8} value={teleForm.roomKey} onChange={e=>setTeleForm({...teleForm,roomKey:e.target.value})}/></label><label className="check"><input type="checkbox" checked={teleForm.recordingEnabled} onChange={e=>setTeleForm({...teleForm,recordingEnabled:e.target.checked})}/>Gravação mediante consentimento</label><label className="check"><input type="checkbox" checked={teleForm.paymentRequired} onChange={e=>setTeleForm({...teleForm,paymentRequired:e.target.checked})}/>Exigir pré-pagamento</label><button className="primary-button compact">Criar sala</button><p>{telehealth.length} teleconsulta(s) registradas.</p></form></div>}
 {tab==="Medplum"&&<section className="panel medplum-panel"><span className="eyebrow">FHIR R4 self-hosted</span><h2>Fundação clínica Medplum</h2><div className={`integration-state ${medplum?.connected?"connected":""}`}><b>{medplum?.connected?"Conectado":"Aguardando configuração"}</b><span>{medplum?.baseUrl}</span>{medplum?.error&&<small>{medplum.error}</small>}</div><p>A ponte agora sincroniza automaticamente pacientes, agenda, atendimentos, diagnósticos, alergias, prescrições, exames, documentos e proveniência.</p>{fhirSync&&<><div className="enterprise-kpis"><article><span>Sincronizados</span><b>{fhirSync.summary.completed}</b></article><article><span>Pendentes</span><b>{fhirSync.summary.pending+fhirSync.summary.processing}</b></article><article><span>Com falha</span><b>{fhirSync.summary.failed}</b><small>Retentativa segura e idempotente</small></article></div><div className="medplum-sync-actions"><button className="secondary-button compact" onClick={()=>void run(()=>api("/v2/medplum/sync/all",{method:"POST"}),"Sincronização inicial processada.")}>Sincronizar base existente</button>{fhirSync.summary.failed>0&&<button className="primary-button compact" onClick={()=>void run(()=>api("/v2/medplum/sync/retry",{method:"POST"}),"Sincronização FHIR reprocessada.")}>Tentar novamente</button>}</div><div className="enterprise-list">{fhirSync.items.slice(0,10).map(item=><div className="enterprise-row" key={`${item.local_resource_type}-${item.local_resource_id}`}><b>{item.local_resource_type}</b><span>{item.status}</span><span>{item.last_synced_at?new Date(item.last_synced_at).toLocaleString("pt-BR"):"Aguardando"}</span>{item.last_error&&<small>{item.last_error}</small>}</div>)}</div></>}<div className="medplum-capabilities">{["Patient","Appointment","Encounter","Composition","Condition","AllergyIntolerance","MedicationRequest","ServiceRequest","DocumentReference","Provenance"].map(resource=><span key={resource}>{resource}</span>)}</div></section>}
 </div>;
}
