import { FormEvent,useEffect,useMemo,useState } from "react";
const apiUrl=import.meta.env.VITE_API_URL??"http://localhost:4000";
type Appointment={id:string;starts_at:string;ends_at:string;type:string;status:string;professional_name:string;unit_name:string};
type Portal={clinic:{name:string};patient:{id:string;full_name:string;preferred_name:string|null;birth_date:string;phone:string;email:string|null;address:Record<string,string>|null;insurance:unknown};appointments:Appointment[];dependents:Array<{id:string;full_name:string;birth_date:string;relationship:string;active:boolean}>;documents:Array<{id:string;category:string;title:string;content:{body?:string;cid?:string;notes?:string};content_hash:string;finalized_at:string;author_name:string}>;finances:Array<{id:string;description:string;amount:string;due_date:string;status:string;paid_at:string|null;payment_method:string|null}>;forms:Array<{id:string;title:string;description:string;fields:Array<{id:string;label:string;type:string;required:boolean}>;response_id:string|null;submitted_at:string|null;appointment_id:string|null}>};
async function api<T>(path:string,init?:RequestInit){const response=await fetch(`${apiUrl}${path}`,{credentials:"include",...init,headers:init?.body?{"Content-Type":"application/json"}:undefined});const payload=await response.json().catch(()=>({})) as T&{error?:string};if(!response.ok)throw new Error(payload.error??"request_failed");return payload;}
const money=(value:string|number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value));
const dateTime=(value:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"long",timeStyle:"short"}).format(new Date(value));
const statusLabels:Record<string,string>={scheduled:"Agendado",confirmed:"Confirmado",waiting:"Aguardando",in_progress:"Em atendimento",completed:"Concluído",cancelled:"Cancelado",no_show:"Faltou",pending:"Pendente",paid:"Pago"};

export function PatientPortalPage({slug}:{slug:string}){
 const[portal,setPortal]=useState<Portal|null>(null);const[step,setStep]=useState<"identify"|"code">("identify");const[tab,setTab]=useState<"appointments"|"forms"|"documents"|"finance"|"profile"|"family">("appointments");const[form,setForm]=useState({tenantSlug:slug,phone:"",birthDate:"",code:""});const[developmentCode,setDevelopmentCode]=useState("");const[error,setError]=useState("");const[message,setMessage]=useState("");const[answers,setAnswers]=useState<Record<string,Record<string,string|boolean|number>>>({});
 const load=()=>api<Portal>("/v1/patient-portal/me").then(value=>{setPortal(value);setError("");}).catch(()=>undefined);useEffect(()=>{void load();},[]);
 const requestCode=async(event:FormEvent)=>{event.preventDefault();setError("");try{const result=await api<{developmentCode?:string}>("/v1/patient-portal/request-code",{method:"POST",body:JSON.stringify({tenantSlug:slug,phone:form.phone,birthDate:form.birthDate})});setDevelopmentCode(result.developmentCode??"");setStep("code");}catch{setError("Não foi possível solicitar o acesso. Confira os dados informados.");}};
 const verify=async(event:FormEvent)=>{event.preventDefault();setError("");try{await api("/v1/patient-portal/verify-code",{method:"POST",body:JSON.stringify(form)});await load();}catch{setError("Código inválido ou expirado.");}};
 const cancel=async(id:string)=>{if(!confirm("Deseja cancelar este agendamento?"))return;try{await api(`/v1/patient-portal/appointments/${id}/cancel`,{method:"PATCH"});setMessage("Agendamento cancelado e clínica informada.");await load();}catch{setError("Este agendamento não pode mais ser cancelado pelo portal.");}};
 const switchPatient=async(patientId:string)=>{await api("/v1/patient-portal/switch-patient",{method:"POST",body:JSON.stringify({patientId})});setTab("appointments");await load();};
 const logout=async()=>{await api("/v1/patient-portal/logout",{method:"POST"});setPortal(null);setStep("identify");};
 const submitForm=async(template:Portal["forms"][number])=>{try{await api(`/v1/patient-portal/forms/${template.id}/responses`,{method:"POST",body:JSON.stringify({appointmentId:template.appointment_id??undefined,answers:answers[template.id]??{}})});setMessage("Formulário enviado para a equipe clínica.");await load();}catch{setError("Não foi possível enviar o formulário.");}};
 const finance=useMemo(()=>({pending:portal?.finances.filter(item=>item.status==="pending").reduce((sum,item)=>sum+Number(item.amount),0)??0,paid:portal?.finances.filter(item=>item.status==="paid").reduce((sum,item)=>sum+Number(item.amount),0)??0}),[portal]);
 if(!portal)return <PortalLogin slug={slug} step={step} form={form} setForm={setForm} developmentCode={developmentCode} error={error} requestCode={requestCode} verify={verify} setStep={setStep}/>;
 return <main className="patient-public-page portal-v25"><section className="portal-dashboard"><header><div><span className="eyebrow">{portal.clinic.name} · Portal do paciente</span><h1>Olá, {portal.patient.preferred_name||portal.patient.full_name.split(" ")[0]}</h1></div><img src="/prontuvia-symbol.png"/></header><div className="portal-account-bar"><label>Perfil ativo<select value={portal.patient.id} onChange={event=>void switchPatient(event.target.value)}>{portal.dependents.map(item=><option key={item.id} value={item.id}>{item.full_name} · {item.relationship}</option>)}</select></label><button type="button" onClick={()=>void logout()}>Sair com segurança</button></div><nav className="portal-tabs">{([['appointments','Agenda'],['forms','Pré-consulta'],['documents','Documentos'],['finance','Financeiro'],['profile','Meus dados'],['family','Dependentes']] as const).map(item=><button type="button" className={tab===item[0]?"active":""} onClick={()=>setTab(item[0])} key={item[0]}>{item[1]}</button>)}</nav>{error&&<div className="form-message error">{error}</div>}{message&&<div className="form-message success">{message}</div>}
 {tab==="appointments"&&<PortalAppointments items={portal.appointments} slug={slug} cancel={cancel}/>} 
 {tab==="forms"&&<section className="portal-section"><div className="portal-section-head"><span className="eyebrow">Antes da consulta</span><h2>Formulários pré-consulta</h2><p>As respostas são enviadas diretamente para a equipe da clínica.</p></div>{portal.forms.map(template=><article className="portal-form-card" key={template.id}><h3>{template.title}</h3><p>{template.description}</p>{template.response_id?<div className="portal-complete">✓ Respondido em {dateTime(template.submitted_at!)}</div>:<>{template.fields.map(field=><label key={field.id}>{field.label}{field.type==="textarea"?<textarea required={field.required} value={String(answers[template.id]?.[field.id]??"")} onChange={event=>setAnswers({...answers,[template.id]:{...(answers[template.id]??{}),[field.id]:event.target.value}})}/>:<input required={field.required} value={String(answers[template.id]?.[field.id]??"")} onChange={event=>setAnswers({...answers,[template.id]:{...(answers[template.id]??{}),[field.id]:event.target.value}})}/>}</label>)}<button className="primary-button compact" type="button" onClick={()=>void submitForm(template)}>Enviar formulário</button></>}</article>)}</section>}
 {tab==="documents"&&<section className="portal-section"><div className="portal-section-head"><span className="eyebrow">Histórico clínico compartilhado</span><h2>Documentos</h2></div>{portal.documents.length?portal.documents.map(document=><details className="portal-document" key={document.id}><summary><div><b>{document.title}</b><small>{document.category} · {dateTime(document.finalized_at)} · {document.author_name}</small></div><span>Abrir</span></summary><div><p>{document.content.body}</p>{document.content.cid&&<b>CID: {document.content.cid}</b>}{document.content.notes&&<p>{document.content.notes}</p>}<small>Integridade: {document.content_hash.slice(0,16)}…</small><button type="button" onClick={()=>window.print()}>Imprimir</button></div></details>):<div className="empty large">Nenhum documento compartilhado.</div>}</section>}
 {tab==="finance"&&<section className="portal-section"><div className="portal-kpis"><article><span>Em aberto</span><b>{money(finance.pending)}</b></article><article><span>Pagamentos registrados</span><b>{money(finance.paid)}</b></article></div>{portal.finances.map(item=><article className="portal-finance-row" key={item.id}><div><b>{item.description}</b><small>Vencimento {new Intl.DateTimeFormat("pt-BR").format(new Date(`${item.due_date}T12:00:00Z`))}</small></div><strong>{money(item.amount)}</strong><span className={`status ${item.status}`}>{statusLabels[item.status]??item.status}</span></article>)}</section>}
 {tab==="profile"&&<PortalProfile patient={portal.patient} saved={async()=>{setMessage("Dados atualizados.");await load();}}/>}
 {tab==="family"&&<PortalFamily dependents={portal.dependents} saved={async()=>{setMessage("Dependente adicionado.");await load();}}/>}
 </section></main>;
}

function PortalAppointments({items,slug,cancel}:{items:Appointment[];slug:string;cancel:(id:string)=>Promise<void>}){const upcoming=items.filter(item=>new Date(item.starts_at)>new Date()&&!['cancelled','no_show'].includes(item.status));const history=items.filter(item=>!upcoming.includes(item));return <section className="portal-section"><div className="portal-section-head"><span className="eyebrow">Sua jornada de cuidado</span><h2>Próximos atendimentos</h2></div>{upcoming.length?upcoming.map(item=><article className="portal-appointment" key={item.id}><div><b>{item.type}</b><span>{item.professional_name} · {item.unit_name}</span><small>{dateTime(item.starts_at)}</small></div><span className={`status ${item.status}`}>{statusLabels[item.status]??item.status}</span><button onClick={()=>void cancel(item.id)}>Cancelar</button></article>):<div className="empty">Nenhum atendimento futuro.</div>}<a className="primary-button portal-new-booking" href={`/agendar/${slug}`}>Novo agendamento</a><div className="portal-section-head history"><h2>Histórico</h2></div>{history.map(item=><article className="portal-appointment compact" key={item.id}><div><b>{item.type}</b><small>{dateTime(item.starts_at)} · {item.professional_name}</small></div><span className={`status ${item.status}`}>{statusLabels[item.status]??item.status}</span></article>)}</section>}

function PortalProfile({patient,saved}:{patient:Portal['patient'];saved:()=>Promise<void>}){const[form,setForm]=useState({preferredName:patient.preferred_name??"",phone:patient.phone??"",email:patient.email??"",street:patient.address?.street??"",number:patient.address?.number??"",city:patient.address?.city??"",state:patient.address?.state??"",zipCode:patient.address?.zipCode??""});const submit=async(event:FormEvent)=>{event.preventDefault();await api("/v1/patient-portal/profile",{method:"PATCH",body:JSON.stringify({preferredName:form.preferredName||undefined,phone:form.phone,email:form.email,address:{street:form.street,number:form.number,city:form.city,state:form.state,zipCode:form.zipCode}})});await saved();};return <section className="portal-section"><div className="portal-section-head"><span className="eyebrow">Cadastro</span><h2>Meus dados</h2><p>Nome civil e data de nascimento devem ser alterados diretamente com a clínica.</p></div><form className="portal-profile-form" onSubmit={submit}><label>Nome preferido<input value={form.preferredName} onChange={e=>setForm({...form,preferredName:e.target.value})}/></label><label>WhatsApp<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>CEP<input value={form.zipCode} onChange={e=>setForm({...form,zipCode:e.target.value})}/></label><label className="wide">Endereço<input value={form.street} onChange={e=>setForm({...form,street:e.target.value})}/></label><label>Número<input value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></label><label>Cidade<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>UF<input maxLength={2} value={form.state} onChange={e=>setForm({...form,state:e.target.value.toUpperCase()})}/></label><button className="primary-button compact">Salvar meus dados</button></form></section>}

function PortalFamily({dependents,saved}:{dependents:Portal['dependents'];saved:()=>Promise<void>}){const[form,setForm]=useState({fullName:"",birthDate:"",relationship:"Filho(a)",sexAtBirth:"unknown"});const submit=async(event:FormEvent)=>{event.preventDefault();await api("/v1/patient-portal/dependents",{method:"POST",body:JSON.stringify(form)});setForm({fullName:"",birthDate:"",relationship:"Filho(a)",sexAtBirth:"unknown"});await saved();};return <section className="portal-section"><div className="portal-section-head"><span className="eyebrow">Responsáveis e menores</span><h2>Dependentes</h2></div><div className="portal-dependent-list">{dependents.map(item=><article key={item.id}><b>{item.full_name}</b><small>{item.relationship} · nascimento {new Intl.DateTimeFormat("pt-BR").format(new Date(`${item.birth_date}T12:00:00Z`))}</small></article>)}</div><form className="portal-profile-form dependent-form" onSubmit={submit}><h3>Novo dependente</h3><label className="wide">Nome completo<input value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} required/></label><label>Nascimento<input type="date" value={form.birthDate} onChange={e=>setForm({...form,birthDate:e.target.value})} required/></label><label>Relação<input value={form.relationship} onChange={e=>setForm({...form,relationship:e.target.value})} required/></label><label>Sexo ao nascer<select value={form.sexAtBirth} onChange={e=>setForm({...form,sexAtBirth:e.target.value})}><option value="unknown">Não informado</option><option value="female">Feminino</option><option value="male">Masculino</option><option value="intersex">Intersexo</option></select></label><button className="primary-button compact">Adicionar dependente</button></form></section>}

function PortalLogin({slug,step,form,setForm,developmentCode,error,requestCode,verify,setStep}:{slug:string;step:"identify"|"code";form:{tenantSlug:string;phone:string;birthDate:string;code:string};setForm:(value:typeof form)=>void;developmentCode:string;error:string;requestCode:(event:FormEvent)=>Promise<void>;verify:(event:FormEvent)=>Promise<void>;setStep:(value:"identify"|"code")=>void}){return <main className="patient-public-page"><section className="public-patient-card portal-login"><img src="/prontuvia-symbol.png"/><span className="eyebrow">Portal do paciente</span><h1>Acesse sua área de cuidado</h1><p>Agendamentos, formulários, documentos e informações financeiras em um só lugar.</p>{error&&<div className="form-message error">{error}</div>}{step==="identify"?<form onSubmit={requestCode}><label>WhatsApp cadastrado<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required/></label><label>Data de nascimento<input type="date" value={form.birthDate} onChange={e=>setForm({...form,birthDate:e.target.value})} required/></label><button className="primary-button">Receber código de acesso</button></form>:<form onSubmit={verify}><p>Enviamos um código de seis dígitos para o contato cadastrado.</p>{developmentCode&&<div className="sandbox-code">Código local: <b>{developmentCode}</b></div>}<label>Código<input inputMode="numeric" maxLength={6} value={form.code} onChange={e=>setForm({...form,code:e.target.value.replace(/\D/g,"")})} required/></label><button className="primary-button">Entrar no portal</button><button type="button" className="secondary-button" onClick={()=>setStep("identify")}>Voltar</button></form>}<a href={`/agendar/${slug}`}>Fazer novo agendamento</a></section></main>}
