import { FormEvent, useEffect, useState } from "react";
const apiUrl=import.meta.env.VITE_API_URL??"http://localhost:4000";
type Plan={code:string;name:string;description:string;price_monthly:string|null;trial_days:number;limits:{users:number;units:number;storageGb:number};features:string[]};
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${apiUrl}${path}`,{credentials:"include",headers:{"Content-Type":"application/json"},...init});const payload=await response.json().catch(()=>({})) as T&{error?:string};if(!response.ok)throw new Error(payload.error??"signup_failed");return payload;}
export function SignupPage({back,initialPlan="professional"}:{back:()=>void;initialPlan?:string}){const[plans,setPlans]=useState<Plan[]>([]);const[step,setStep]=useState<1|2>(1);const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[form,setForm]=useState({name:"",email:"",password:"",displayName:"",slug:"",entityType:"clinic",planCode:initialPlan,acceptTerms:false});useEffect(()=>{api<{items:Plan[]}>("/v1/commercial/plans").then(d=>setPlans(d.items)).catch(()=>setError("Execute as migrações da v1.0 para carregar os planos."));},[]);
 const setDisplay=(value:string)=>setForm({...form,displayName:value,slug:value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")});
 const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError("");try{await api("/v1/commercial/signup",{method:"POST",body:JSON.stringify({...form,entityType:form.entityType})});window.location.reload();}catch(err){const code=err instanceof Error?err.message:"signup_failed";setError(code==="email_already_registered"?"Este e-mail já possui uma conta.":code==="clinic_slug_exists"?"Este identificador de clínica já está em uso.":"Não foi possível concluir o cadastro.");setLoading(false);}};
 return <main className="signup-page"><header><div><img src="/prontuvia-symbol.png"/><b>Prontuvia</b></div><button onClick={back}>Já tenho uma conta</button></header><form className="signup-card" onSubmit={submit}><span className="eyebrow">Comece seu período de avaliação</span><h1>{step===1?"Escolha o plano":"Crie sua conta"}</h1>{step===1?<><div className="public-plans">{plans.map(plan=><button type="button" key={plan.code} className={form.planCode===plan.code?"selected":""} onClick={()=>setForm({...form,planCode:plan.code})}><span>{plan.name}</span><b>{plan.price_monthly?`R$ ${Number(plan.price_monthly).toFixed(2).replace(".",",")}/mês`:"Preço configurável"}</b><p>{plan.description}</p><small>{plan.trial_days} dias de teste · {plan.limits.users} usuários · {plan.limits.units} unidade(s)</small></button>)}</div><button type="button" className="primary-button signup-next" onClick={()=>setStep(2)} disabled={!plans.length}>Continuar</button></>:<><div className="signup-grid"><label>Seu nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Senha<input type="password" minLength={10} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label><label>Tipo de contratação<select value={form.entityType} onChange={e=>setForm({...form,entityType:e.target.value})}><option value="clinic">Clínica ou consultório</option><option value="individual">Médico/profissional autônomo</option></select></label><label>Nome que aparecerá nos documentos<input value={form.displayName} onChange={e=>setDisplay(e.target.value)} placeholder={form.entityType==="individual"?"Dr. Nome Sobrenome":"Nome da clínica"} required/></label><label>Endereço de acesso<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"")})} required/><small>{form.slug||"sua-clinica"}</small></label></div><label className="terms-check"><input type="checkbox" checked={form.acceptTerms} onChange={e=>setForm({...form,acceptTerms:e.target.checked})} required/>Li e aceito os Termos de Uso e a Política de Privacidade.</label>{error&&<div className="form-message error">{error}</div>}<div className="signup-actions"><button type="button" className="secondary-button" onClick={()=>setStep(1)}>Voltar</button><button className="primary-button" disabled={loading}>{loading?"Criando ambiente…":"Criar minha conta"}</button></div></>}</form></main>;
}
