import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { z } from "zod";
import { authenticate } from "../auth.js";
import { withTenant } from "../db.js";
import { writeAudit } from "../audit.js";
import { config } from "../config.js";
import { createHash } from "node:crypto";

const idParam = z.object({ id: z.uuid() });
const periodQuery = z.object({ from: z.iso.date().optional(), to: z.iso.date().optional() });
const operatorInput = z.object({ name: z.string().trim().min(2).max(160), ansRegistry: z.string().trim().min(3).max(30), tissVersion: z.string().trim().default("4.01.00"), appealDeadlineDays: z.number().int().min(1).max(365).default(30) });
const guideInput = z.object({ operatorId: z.uuid(), patientId: z.uuid().optional(), appointmentId: z.uuid().optional(), guideType: z.enum(["consultation","sadt","fees","hospitalization","dental","appeal"]), guideNumber: z.string().trim().min(2).max(80), beneficiaryNumber: z.string().trim().max(80).optional(), authorizationNumber: z.string().trim().max(80).optional(), totalAmount: z.number().nonnegative(), items: z.array(z.object({ tussCode: z.string().trim().min(2).max(30), description: z.string().trim().min(2).max(240), quantity: z.number().positive(), unitPrice: z.number().nonnegative() })).default([]) });
const denialInput = z.object({ guideId: z.uuid(), reasonCode: z.string().trim().min(1).max(30), reasonDescription: z.string().trim().min(2).max(500), deniedAmount: z.number().positive(), category: z.enum(["administrative","technical","contractual","table_difference"]).default("administrative"), appealDeadline: z.iso.date().optional() });
const appealInput = z.object({ denialId: z.uuid(), justification: z.string().trim().min(10).max(10000), evidence: z.array(z.object({ type: z.string(), reference: z.string() })).default([]) });
const invoiceInput = z.object({ patientId: z.uuid().optional(), financialTransactionId: z.uuid().optional(), kind: z.enum(["service","product"]), amount: z.number().positive() });
const reconciliationInput = z.object({ bankAccountId: z.uuid().optional(), filename: z.string().trim().min(1).max(240), fileSha256: z.string().regex(/^[a-f0-9]{64}$/i), periodStart: z.iso.date().optional(), periodEnd: z.iso.date().optional(), items: z.array(z.object({ occurredOn: z.iso.date(), description: z.string().trim().min(1).max(500), amount: z.number().refine((value) => value !== 0), externalReference: z.string().max(200).optional() })).default([]) });
const ofxInput = z.object({ bankAccountId: z.uuid().optional(), filename: z.string().trim().min(1).max(240), content: z.string().min(20).max(5_000_000) });
const reconcileMatchInput = z.object({ transactionId: z.uuid().optional(), action: z.enum(["match","ignore"]) });
const migrationInput = z.object({ source: z.enum(["iclinic","feegow","amplimed","prodoctor","csv","fhir"]), filename: z.string().trim().min(1).max(240) });
const migrationRunInput = z.object({ csv: z.string().min(3).max(10_000_000), dryRun: z.boolean().default(true) });
const inventoryInput = z.object({ name: z.string().trim().min(2).max(160), sku: z.string().trim().min(1).max(80), unit: z.string().trim().min(1).max(20).default("un"), minimumQuantity: z.number().nonnegative().default(0), averageCost: z.number().nonnegative().default(0) });
const movementInput = z.object({ itemId: z.uuid(), kind: z.enum(["entry","exit","adjustment"]), quantity: z.number().positive(), unitCost: z.number().nonnegative().optional(), lot: z.string().max(100).optional(), expiresOn: z.iso.date().optional(), reason: z.string().trim().min(2).max(240) });
const aiInput = z.object({ patientId: z.uuid().optional(), encounterId: z.uuid().optional(), kind: z.enum(["ambient_note","summary","coding","no_show","financial_anomaly","denial_risk"]), inputReference: z.record(z.string(), z.unknown()).default({}) });
const telehealthInput = z.object({ appointmentId: z.uuid(), roomKey: z.string().trim().min(8).max(120), recordingEnabled: z.boolean().default(false), paymentRequired: z.boolean().default(false) });

function requireFinanceManagement(request: FastifyRequest, reply: FastifyReply): void {
  if (!["owner", "admin", "finance"].includes(request.auth.role)) reply.code(403).send({ error: "permission_denied" });
}
function requireOwnerAdmin(request: FastifyRequest, reply: FastifyReply): void {
  if (!["owner", "admin"].includes(request.auth.role)) reply.code(403).send({ error: "permission_denied" });
}

export async function advancedRoutes(app: FastifyInstance): Promise<void> {
  app.addHook("preHandler", authenticate);

  app.get("/overview", async (request) => withTenant(request.auth, async (client) => {
    const [tiss, denials, fiscal, reconciliation, migrations, stock, ai, telehealth] = await Promise.all([
      client.query("SELECT count(*)::int AS total,coalesce(sum(total_amount),0) AS amount,count(*) FILTER(WHERE status IN('draft','validation','ready'))::int AS pending FROM tiss_guides WHERE tenant_id=$1", [request.auth.tenantId]),
      client.query("SELECT count(*)::int AS total,coalesce(sum(denied_amount),0) AS denied,coalesce(sum((SELECT coalesce(sum(recovered_amount),0) FROM tiss_appeals a WHERE a.tenant_id=d.tenant_id AND a.denial_id=d.id)),0) AS recovered,count(*) FILTER(WHERE status NOT IN('recovered','rejected','accepted_loss'))::int AS open FROM tiss_denials d WHERE tenant_id=$1", [request.auth.tenantId]),
      client.query("SELECT count(*)::int AS total,coalesce(sum(amount) FILTER(WHERE status='authorized'),0) AS authorized,count(*) FILTER(WHERE status IN('draft','queued','processing'))::int AS pending FROM fiscal_invoices WHERE tenant_id=$1", [request.auth.tenantId]),
      client.query("SELECT count(*) FILTER(WHERE status='matched')::int AS matched,count(*) FILTER(WHERE status='unmatched')::int AS unmatched FROM bank_statement_items WHERE tenant_id=$1", [request.auth.tenantId]),
      client.query("SELECT count(*)::int AS total,count(*) FILTER(WHERE status='completed')::int AS completed,count(*) FILTER(WHERE status='failed')::int AS failed FROM migration_jobs WHERE tenant_id=$1", [request.auth.tenantId]),
      client.query("SELECT count(*)::int AS total,count(*) FILTER(WHERE current_quantity<=minimum_quantity)::int AS low_stock,coalesce(sum(current_quantity*average_cost),0) AS stock_value FROM inventory_items WHERE tenant_id=$1 AND status='active'", [request.auth.tenantId]),
      client.query("SELECT count(*)::int AS total,count(*) FILTER(WHERE status='review')::int AS awaiting_review FROM ai_jobs WHERE tenant_id=$1", [request.auth.tenantId]),
      client.query("SELECT count(*)::int AS total,count(*) FILTER(WHERE status IN('scheduled','waiting','in_progress'))::int AS active FROM teleconsultations WHERE tenant_id=$1", [request.auth.tenantId]),
    ]);
    return { tiss: tiss.rows[0], denials: denials.rows[0], fiscal: fiscal.rows[0], reconciliation: reconciliation.rows[0], migrations: migrations.rows[0], stock: stock.rows[0], ai: ai.rows[0], telehealth: telehealth.rows[0], integrations: { medplum: Boolean(config.MEDPLUM_CLIENT_ID), nfse: config.NFSE_PROVIDER, bank: config.BANK_RECONCILIATION_PROVIDER, ai: config.AI_PROVIDER } };
  }));

  app.get("/tiss/operators", async (request) => withTenant(request.auth, (client) => client.query("SELECT * FROM tiss_operators WHERE tenant_id=$1 ORDER BY name", [request.auth.tenantId]).then((r) => ({ items: r.rows }))));
  app.post("/tiss/operators", { preHandler: [requireFinanceManagement] }, async (request, reply) => { const input = operatorInput.parse(request.body); return withTenant(request.auth, async (client) => { const r = await client.query<{id:string}>("INSERT INTO tiss_operators(tenant_id,name,ans_registry,tiss_version,appeal_deadline_days) VALUES($1,$2,$3,$4,$5) RETURNING id", [request.auth.tenantId,input.name,input.ansRegistry,input.tissVersion,input.appealDeadlineDays]); return reply.code(201).send({ id:r.rows[0]!.id }); }); });
  app.get("/tiss/guides", async (request) => withTenant(request.auth, (client) => client.query("SELECT g.*,o.name AS operator_name,p.full_name AS patient_name FROM tiss_guides g JOIN tiss_operators o ON o.tenant_id=g.tenant_id AND o.id=g.operator_id LEFT JOIN patients p ON p.tenant_id=g.tenant_id AND p.id=g.patient_id WHERE g.tenant_id=$1 ORDER BY g.created_at DESC LIMIT 200", [request.auth.tenantId]).then((r) => ({ items:r.rows }))));
  app.post("/tiss/guides", { preHandler:[requireFinanceManagement] }, async (request,reply) => { const input=guideInput.parse(request.body); return withTenant(request.auth,async(client)=>{ const calculated=input.items.reduce((sum,item)=>sum+item.quantity*item.unitPrice,0); const findings:string[]=[]; if(!input.beneficiaryNumber)findings.push("Carteirinha do beneficiário não informada"); if(input.items.length===0)findings.push("Guia sem itens TUSS"); const risk=Math.min(100,findings.length*35); const r=await client.query<{id:string}>("INSERT INTO tiss_guides(tenant_id,operator_id,patient_id,appointment_id,guide_type,guide_number,beneficiary_number,authorization_number,total_amount,risk_score,validation_findings,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id",[request.auth.tenantId,input.operatorId,input.patientId??null,input.appointmentId??null,input.guideType,input.guideNumber,input.beneficiaryNumber??null,input.authorizationNumber??null,input.totalAmount||calculated,risk,JSON.stringify(findings),findings.length?"validation":"ready"]); for(const item of input.items)await client.query("INSERT INTO tiss_guide_items(tenant_id,guide_id,tuss_code,description,quantity,unit_price) VALUES($1,$2,$3,$4,$5,$6)",[request.auth.tenantId,r.rows[0]!.id,item.tussCode,item.description,item.quantity,item.unitPrice]); return reply.code(201).send({id:r.rows[0]!.id,riskScore:risk,findings}); }); });
  app.get("/tiss/denials", async(request)=>withTenant(request.auth,(client)=>client.query("SELECT d.*,g.guide_number,o.name AS operator_name FROM tiss_denials d JOIN tiss_guides g ON g.tenant_id=d.tenant_id AND g.id=d.guide_id JOIN tiss_operators o ON o.tenant_id=g.tenant_id AND o.id=g.operator_id WHERE d.tenant_id=$1 ORDER BY d.appeal_deadline NULLS LAST,d.created_at DESC",[request.auth.tenantId]).then(r=>({items:r.rows}))));
  app.post("/tiss/denials",{preHandler:[requireFinanceManagement]},async(request,reply)=>{const input=denialInput.parse(request.body);return withTenant(request.auth,async client=>{const r=await client.query<{id:string}>("INSERT INTO tiss_denials(tenant_id,guide_id,reason_code,reason_description,denied_amount,category,appeal_deadline) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id",[request.auth.tenantId,input.guideId,input.reasonCode,input.reasonDescription,input.deniedAmount,input.category,input.appealDeadline??null]);return reply.code(201).send({id:r.rows[0]!.id});});});
  app.post("/tiss/appeals",{preHandler:[requireFinanceManagement]},async(request,reply)=>{const input=appealInput.parse(request.body);return withTenant(request.auth,async client=>{const r=await client.query<{id:string}>("INSERT INTO tiss_appeals(tenant_id,denial_id,justification,evidence,created_by) VALUES($1,$2,$3,$4,$5) RETURNING id",[request.auth.tenantId,input.denialId,input.justification,JSON.stringify(input.evidence),request.auth.userId]);await client.query("UPDATE tiss_denials SET status='appealed' WHERE tenant_id=$1 AND id=$2",[request.auth.tenantId,input.denialId]);return reply.code(201).send({id:r.rows[0]!.id});});});

  app.get("/fiscal",async(request)=>withTenant(request.auth,(client)=>client.query("SELECT f.*,p.full_name AS patient_name FROM fiscal_invoices f LEFT JOIN patients p ON p.tenant_id=f.tenant_id AND p.id=f.patient_id WHERE f.tenant_id=$1 ORDER BY f.created_at DESC LIMIT 200",[request.auth.tenantId]).then(r=>({items:r.rows}))));
  app.post("/fiscal",{preHandler:[requireFinanceManagement]},async(request,reply)=>{const input=invoiceInput.parse(request.body);return withTenant(request.auth,async client=>{const initialStatus=config.NFSE_PROVIDER==='sandbox'?'authorized':'queued';const r=await client.query<{id:string}>("INSERT INTO fiscal_invoices(tenant_id,patient_id,financial_transaction_id,kind,provider,amount,status,invoice_number,verification_code,issued_at) VALUES($1,$2,$3,$4,$5,$6,$7,CASE WHEN $7='authorized' THEN 'SANDBOX-'||to_char(now(),'YYYYMMDDHH24MISS') END,CASE WHEN $7='authorized' THEN upper(substr(md5(random()::text),1,8)) END,CASE WHEN $7='authorized' THEN now() END) RETURNING id,status,invoice_number",[request.auth.tenantId,input.patientId??null,input.financialTransactionId??null,input.kind,config.NFSE_PROVIDER,input.amount,initialStatus]);return reply.code(201).send(r.rows[0]);});});

  app.get("/reconciliation",async(request)=>withTenant(request.auth,(client)=>client.query("SELECT i.*,b.filename FROM bank_statement_items i JOIN bank_statement_imports b ON b.tenant_id=i.tenant_id AND b.id=i.import_id WHERE i.tenant_id=$1 ORDER BY i.occurred_on DESC LIMIT 500",[request.auth.tenantId]).then(r=>({items:r.rows}))));
  app.post("/reconciliation/imports",{preHandler:[requireFinanceManagement]},async(request,reply)=>{const input=reconciliationInput.parse(request.body);return withTenant(request.auth,async client=>{const r=await client.query<{id:string}>("INSERT INTO bank_statement_imports(tenant_id,bank_account_id,filename,file_sha256,period_start,period_end,status,created_by) VALUES($1,$2,$3,$4,$5,$6,'ready',$7) RETURNING id",[request.auth.tenantId,input.bankAccountId??null,input.filename,input.fileSha256.toLowerCase(),input.periodStart??null,input.periodEnd??null,request.auth.userId]);for(const item of input.items)await client.query("INSERT INTO bank_statement_items(tenant_id,import_id,occurred_on,description,amount,external_reference) VALUES($1,$2,$3,$4,$5,$6)",[request.auth.tenantId,r.rows[0]!.id,item.occurredOn,item.description,item.amount,item.externalReference??null]);return reply.code(201).send({id:r.rows[0]!.id,items:input.items.length});});});
  app.post("/reconciliation/ofx",{preHandler:[requireFinanceManagement]},async(request,reply)=>{const input=ofxInput.parse(request.body);const blocks=input.content.match(/<STMTTRN>[\s\S]*?(?=<STMTTRN>|<\/BANKTRANLIST>|$)/gi)??[];const items=blocks.map(block=>{const get=(tag:string)=>block.match(new RegExp(`<${tag}>([^<\\r\\n]+)`,`i`))?.[1]?.trim();const rawDate=get('DTPOSTED')??'';return{occurredOn:rawDate.length>=8?`${rawDate.slice(0,4)}-${rawDate.slice(4,6)}-${rawDate.slice(6,8)}`:new Date().toISOString().slice(0,10),description:get('MEMO')??get('NAME')??'Movimentação OFX',amount:Number(get('TRNAMT')??0),externalReference:get('FITID')};}).filter(item=>Number.isFinite(item.amount)&&item.amount!==0);const hash=createHash('sha256').update(input.content).digest('hex');return withTenant(request.auth,async client=>{const r=await client.query<{id:string}>("INSERT INTO bank_statement_imports(tenant_id,bank_account_id,filename,file_sha256,period_start,period_end,status,created_by) VALUES($1,$2,$3,$4,$5,$6,'ready',$7) RETURNING id",[request.auth.tenantId,input.bankAccountId??null,input.filename,hash,items[0]?.occurredOn??null,items.at(-1)?.occurredOn??null,request.auth.userId]);for(const item of items)await client.query("INSERT INTO bank_statement_items(tenant_id,import_id,occurred_on,description,amount,external_reference) VALUES($1,$2,$3,$4,$5,$6)",[request.auth.tenantId,r.rows[0]!.id,item.occurredOn,item.description,item.amount,item.externalReference??null]);return reply.code(201).send({id:r.rows[0]!.id,items:items.length});});});
  app.patch("/reconciliation/items/:id",{preHandler:[requireFinanceManagement]},async(request,reply)=>{const{id}=idParam.parse(request.params);const input=reconcileMatchInput.parse(request.body);return withTenant(request.auth,async client=>{const r=await client.query("UPDATE bank_statement_items SET status=$1,matched_transaction_id=$2 WHERE tenant_id=$3 AND id=$4 RETURNING id,status",[input.action==='match'?'matched':'ignored',input.action==='match'?input.transactionId??null:null,request.auth.tenantId,id]);if(!r.rows[0])return reply.code(404).send({error:'statement_item_not_found'});return r.rows[0];});});

  app.get("/migrations",async(request)=>withTenant(request.auth,(client)=>client.query("SELECT * FROM migration_jobs WHERE tenant_id=$1 ORDER BY created_at DESC",[request.auth.tenantId]).then(r=>({items:r.rows}))));
  app.post("/migrations",{preHandler:[requireOwnerAdmin]},async(request,reply)=>{const input=migrationInput.parse(request.body);return withTenant(request.auth,async client=>{const r=await client.query<{id:string}>("INSERT INTO migration_jobs(tenant_id,source,filename,created_by,status) VALUES($1,$2,$3,$4,'dry_run') RETURNING id,status",[request.auth.tenantId,input.source,input.filename,request.auth.userId]);return reply.code(201).send(r.rows[0]);});});
  app.post("/migrations/:id/run",{preHandler:[requireOwnerAdmin]},async(request,reply)=>{const{id}=idParam.parse(request.params);const input=migrationRunInput.parse(request.body);const lines=input.csv.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);const delimiter=(lines[0]?.match(/;/g)?.length??0)>(lines[0]?.match(/,/g)?.length??0)?';':',';const parse=(line:string)=>{const result:string[]=[];let value='';let quoted=false;for(let index=0;index<line.length;index++){const char=line[index]!;if(char==='"'){if(quoted&&line[index+1]==='"'){value+='"';index++;}else quoted=!quoted;}else if(char===delimiter&&!quoted){result.push(value.trim());value='';}else value+=char;}result.push(value.trim());return result;};const headers=parse(lines.shift()??'').map(header=>header.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,'_'));const records=lines.map(line=>Object.fromEntries(headers.map((header,index)=>[header,parse(line)[index]??''])));const normalized=records.map(record=>({fullName:record.nome_completo||record.nome||record.full_name||record.name,birthDate:record.data_de_nascimento||record.data_nascimento||record.birth_date||null,phone:record.telefone||record.phone||null,email:record.email||null})).filter(record=>record.fullName&&record.fullName.length>=2);return withTenant(request.auth,async client=>{const job=await client.query("SELECT id FROM migration_jobs WHERE tenant_id=$1 AND id=$2",[request.auth.tenantId,id]);if(!job.rows[0])return reply.code(404).send({error:'migration_job_not_found'});if(!input.dryRun){for(const record of normalized)await client.query("INSERT INTO patients(tenant_id,full_name,birth_date,phone,email,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$6)",[request.auth.tenantId,record.fullName,record.birthDate||null,record.phone||null,record.email||null,request.auth.userId]);}await client.query("UPDATE migration_jobs SET status=$1,totals=$2,errors=$3 WHERE tenant_id=$4 AND id=$5",[input.dryRun?'dry_run':'completed',JSON.stringify({rows:records.length,valid:normalized.length,invalid:records.length-normalized.length,imported:input.dryRun?0:normalized.length}),JSON.stringify(records.length===normalized.length?[]:[{message:'Linhas sem nome foram ignoradas'}]),request.auth.tenantId,id]);return{dryRun:input.dryRun,rows:records.length,valid:normalized.length,invalid:records.length-normalized.length,imported:input.dryRun?0:normalized.length};});});

  app.get("/inventory",async(request)=>withTenant(request.auth,(client)=>client.query("SELECT * FROM inventory_items WHERE tenant_id=$1 ORDER BY name",[request.auth.tenantId]).then(r=>({items:r.rows}))));
  app.post("/inventory",{preHandler:[requireFinanceManagement]},async(request,reply)=>{const input=inventoryInput.parse(request.body);return withTenant(request.auth,async client=>{const r=await client.query<{id:string}>("INSERT INTO inventory_items(tenant_id,name,sku,unit,minimum_quantity,average_cost) VALUES($1,$2,$3,$4,$5,$6) RETURNING id",[request.auth.tenantId,input.name,input.sku,input.unit,input.minimumQuantity,input.averageCost]);return reply.code(201).send({id:r.rows[0]!.id});});});
  app.post("/inventory/movements",{preHandler:[requireFinanceManagement]},async(request,reply)=>{const input=movementInput.parse(request.body);return withTenant(request.auth,async client=>{const signed=input.kind==='exit'?-input.quantity:input.quantity;const updated=await client.query("UPDATE inventory_items SET current_quantity=current_quantity+$1,average_cost=CASE WHEN $2::numeric IS NULL THEN average_cost ELSE $2 END WHERE tenant_id=$3 AND id=$4 AND current_quantity+$1>=0 RETURNING id",[signed,input.unitCost??null,request.auth.tenantId,input.itemId]);if(!updated.rows[0])return reply.code(409).send({error:'insufficient_stock'});const r=await client.query<{id:string}>("INSERT INTO inventory_movements(tenant_id,item_id,kind,quantity,unit_cost,lot,expires_on,reason,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id",[request.auth.tenantId,input.itemId,input.kind,input.quantity,input.unitCost??null,input.lot??null,input.expiresOn??null,input.reason,request.auth.userId]);return reply.code(201).send({id:r.rows[0]!.id});});});

  app.get("/ai",async(request)=>withTenant(request.auth,(client)=>client.query("SELECT * FROM ai_jobs WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 200",[request.auth.tenantId]).then(r=>({items:r.rows}))));
  app.post("/ai",async(request,reply)=>{const input=aiInput.parse(request.body);return withTenant(request.auth,async client=>{const status=config.AI_PROVIDER==='disabled'?'review':'queued';const output=config.AI_PROVIDER==='disabled'?{notice:'Provedor de IA desativado; item criado para revisão manual.'}:null;const r=await client.query<{id:string}>("INSERT INTO ai_jobs(tenant_id,patient_id,encounter_id,kind,input_reference,output,status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,status",[request.auth.tenantId,input.patientId??null,input.encounterId??null,input.kind,JSON.stringify(input.inputReference),output?JSON.stringify(output):null,status,request.auth.userId]);return reply.code(201).send(r.rows[0]);});});
  app.get("/telehealth",async(request)=>withTenant(request.auth,(client)=>client.query("SELECT t.*,a.starts_at,p.full_name AS patient_name FROM teleconsultations t JOIN appointments a ON a.tenant_id=t.tenant_id AND a.id=t.appointment_id JOIN patients p ON p.tenant_id=a.tenant_id AND p.id=a.patient_id WHERE t.tenant_id=$1 ORDER BY a.starts_at DESC",[request.auth.tenantId]).then(r=>({items:r.rows}))));
  app.post("/telehealth",async(request,reply)=>{const input=telehealthInput.parse(request.body);return withTenant(request.auth,async client=>{const r=await client.query<{id:string}>("INSERT INTO teleconsultations(tenant_id,appointment_id,room_key,recording_enabled,payment_required) VALUES($1,$2,$3,$4,$5) RETURNING id",[request.auth.tenantId,input.appointmentId,input.roomKey,input.recordingEnabled,input.paymentRequired]);return reply.code(201).send({id:r.rows[0]!.id});});});

  app.get("/audit-summary",{preHandler:[requireOwnerAdmin]},async(request)=>{const query=periodQuery.parse(request.query);return withTenant(request.auth,(client)=>client.query("SELECT action,resource_type,count(*)::int AS events,count(DISTINCT actor_user_id)::int AS actors FROM audit_events WHERE tenant_id=$1 AND created_at>=coalesce($2::date,current_date-30) AND created_at<coalesce($3::date,current_date)+1 GROUP BY action,resource_type ORDER BY events DESC",[request.auth.tenantId,query.from??null,query.to??null]).then(r=>({items:r.rows})));});
}
