import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { authenticate } from "../auth.js";
import { requirePermission } from "../authorization.js";
import { writeAudit } from "../audit.js";
import { withTenant } from "../db.js";

const procedureInput=z.object({name:z.string().trim().min(2).max(120),durationMinutes:z.number().int().min(5).max(720),price:z.number().min(0).max(99_999_999_999.99),professionalAmount:z.number().min(0).max(99_999_999_999.99),color:z.string().regex(/^#[0-9A-Fa-f]{6}$/),tussCode:z.string().trim().max(20).optional(),automaticReceivable:z.boolean().default(true),status:z.enum(["active","inactive"]).default("active")}).refine(value=>value.professionalAmount<=value.price,{path:["professionalAmount"],message:"O repasse não pode ser maior que o valor do procedimento"});
const scheduleInput=z.object({professionalUserId:z.uuid(),unitId:z.uuid(),weekday:z.number().int().min(0).max(6),startsAt:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),endsAt:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/)}).refine(v=>v.endsAt>v.startsAt,{path:["endsAt"],message:"Horário final deve ser posterior"});
const blockInput=z.object({professionalUserId:z.uuid(),unitId:z.uuid().optional(),startsAt:z.iso.datetime({offset:true}),endsAt:z.iso.datetime({offset:true}),reason:z.string().trim().min(2).max(180)}).refine(v=>new Date(v.endsAt)>new Date(v.startsAt),{path:["endsAt"],message:"Fim deve ser posterior"});
const idParams=z.object({id:z.uuid()});
const specialtyInput=z.object({name:z.string().trim().min(2).max(120),status:z.enum(["active","inactive"]).default("active")});
const professionalServiceInput=z.object({professionalUserId:z.uuid(),specialtyId:z.uuid(),procedureId:z.uuid(),councilNumber:z.string().trim().max(40).optional(),councilState:z.string().trim().length(2).transform(value=>value.toUpperCase()).optional(),rqe:z.string().trim().max(40).optional(),publicBookingEnabled:z.boolean().default(true)});
const professionalServiceParams=z.object({professionalUserId:z.uuid(),specialtyId:z.uuid(),procedureId:z.uuid()});
function procedureDatabaseError(error:unknown){const databaseError=error as{code?:string;constraint?:string};if(databaseError.code==="23505")return{status:409,error:"procedure_name_exists"};if(databaseError.code==="23514")return{status:400,error:databaseError.constraint==="procedures_professional_amount_within_price"?"procedure_payout_exceeds_price":"procedure_values_invalid"};if(databaseError.code==="42703")return{status:503,error:"procedure_migration_required"};return null;}

export async function operationRoutes(app:FastifyInstance):Promise<void>{
  app.addHook("preHandler",authenticate);
  app.get("/procedures",{preHandler:[requirePermission("appointments.read")]},async request=>withTenant(request.auth,async client=>({items:(await client.query("SELECT id,name,duration_minutes,price,professional_amount,color,tuss_code,automatic_receivable,status FROM procedures WHERE tenant_id=$1 ORDER BY status,name",[request.auth.tenantId])).rows})));
  app.post("/procedures",{preHandler:[requirePermission("tenant.manage")]},async(request,reply)=>{const input=procedureInput.parse(request.body);try{return await withTenant(request.auth,async client=>{const result=await client.query<{id:string}>(`INSERT INTO procedures(tenant_id,name,duration_minutes,price,professional_amount,color,tuss_code,automatic_receivable,status,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$10) RETURNING id`,[request.auth.tenantId,input.name,input.durationMinutes,input.price,input.professionalAmount,input.color,input.tussCode||null,input.automaticReceivable,input.status,request.auth.userId]);const id=result.rows[0]!.id;await writeAudit(client,{tenantId:request.auth.tenantId,actorUserId:request.auth.userId,action:"procedure.create",resourceType:"procedure",resourceId:id,requestId:request.id,ip:request.ip,after:input});return reply.code(201).send({id});});}catch(error){const mapped=procedureDatabaseError(error);if(mapped)return reply.code(mapped.status).send({error:mapped.error});throw error;}});
  app.put("/procedures/:id",{preHandler:[requirePermission("tenant.manage")]},async(request,reply)=>{const{id}=idParams.parse(request.params);const input=procedureInput.parse(request.body);try{return await withTenant(request.auth,async client=>{const current=await client.query("SELECT id FROM procedures WHERE tenant_id=$1 AND id=$2 FOR UPDATE",[request.auth.tenantId,id]);if(!current.rows[0])return reply.code(404).send({error:"procedure_not_found"});const result=await client.query(`UPDATE procedures SET name=$1,duration_minutes=$2,price=$3,professional_amount=$4,color=$5,tuss_code=$6,automatic_receivable=$7,status=$8,updated_by=$9 WHERE tenant_id=$10 AND id=$11 RETURNING id,name,price,professional_amount`,[input.name,input.durationMinutes,input.price,input.professionalAmount,input.color,input.tussCode||null,input.automaticReceivable,input.status,request.auth.userId,request.auth.tenantId,id]);await writeAudit(client,{tenantId:request.auth.tenantId,actorUserId:request.auth.userId,action:"procedure.update",resourceType:"procedure",resourceId:id,requestId:request.id,ip:request.ip,after:input});return{item:result.rows[0]};});}catch(error){const mapped=procedureDatabaseError(error);if(mapped)return reply.code(mapped.status).send({error:mapped.error});throw error;}});
  app.get("/specialties",{preHandler:[requirePermission("appointments.read")]},async request=>withTenant(request.auth,async client=>({items:(await client.query("SELECT id,name,status FROM specialties WHERE tenant_id=$1 ORDER BY status,name",[request.auth.tenantId])).rows})));
  app.post("/specialties",{preHandler:[requirePermission("tenant.manage")]},async(request,reply)=>{const input=specialtyInput.parse(request.body);return withTenant(request.auth,async client=>{const result=await client.query<{id:string}>("INSERT INTO specialties(tenant_id,name,status,created_by,updated_by) VALUES($1,$2,$3,$4,$4) RETURNING id",[request.auth.tenantId,input.name,input.status,request.auth.userId]);await writeAudit(client,{tenantId:request.auth.tenantId,actorUserId:request.auth.userId,action:"specialty.create",resourceType:"specialty",resourceId:result.rows[0]!.id,requestId:request.id,ip:request.ip,after:input});return reply.code(201).send({id:result.rows[0]!.id});});});
  app.put("/specialties/:id",{preHandler:[requirePermission("tenant.manage")]},async(request,reply)=>{const{id}=idParams.parse(request.params);const input=specialtyInput.parse(request.body);return withTenant(request.auth,async client=>{const result=await client.query("UPDATE specialties SET name=$1,status=$2,updated_by=$3 WHERE tenant_id=$4 AND id=$5 RETURNING id",[input.name,input.status,request.auth.userId,request.auth.tenantId,id]);if(!result.rows[0])return reply.code(404).send({error:"specialty_not_found"});return{item:result.rows[0]};});});
  app.get("/professional-services",{preHandler:[requirePermission("appointments.read")]},async request=>withTenant(request.auth,async client=>({items:(await client.query(`SELECT ps.professional_user_id,u.name AS professional_name,ps.specialty_id,s.name AS specialty_name,pv.procedure_id,p.name AS procedure_name,ps.council_number,ps.council_state,ps.rqe,pv.public_booking_enabled FROM professional_services pv JOIN professional_specialties ps ON ps.tenant_id=pv.tenant_id AND ps.professional_user_id=pv.professional_user_id AND ps.specialty_id=pv.specialty_id JOIN users u ON u.id=pv.professional_user_id JOIN specialties s ON s.tenant_id=pv.tenant_id AND s.id=pv.specialty_id JOIN procedures p ON p.tenant_id=pv.tenant_id AND p.id=pv.procedure_id WHERE pv.tenant_id=$1 ORDER BY s.name,u.name,p.name`,[request.auth.tenantId])).rows})));
  app.post("/professional-services",{preHandler:[requirePermission("tenant.manage")]},async(request,reply)=>{const input=professionalServiceInput.parse(request.body);return withTenant(request.auth,async client=>{const valid=await client.query(`SELECT EXISTS(SELECT 1 FROM tenant_memberships WHERE tenant_id=$1 AND user_id=$2 AND status='active' AND role IN('owner','admin','clinician')) AS professional_ok,EXISTS(SELECT 1 FROM specialties WHERE tenant_id=$1 AND id=$3 AND status='active') AS specialty_ok,EXISTS(SELECT 1 FROM procedures WHERE tenant_id=$1 AND id=$4 AND status='active') AS procedure_ok`,[request.auth.tenantId,input.professionalUserId,input.specialtyId,input.procedureId]);if(!valid.rows[0]?.professional_ok||!valid.rows[0]?.specialty_ok||!valid.rows[0]?.procedure_ok)return reply.code(400).send({error:"professional_service_reference_invalid"});await client.query(`INSERT INTO professional_specialties(tenant_id,professional_user_id,specialty_id,council_number,council_state,rqe,public_booking_enabled,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8) ON CONFLICT(tenant_id,professional_user_id,specialty_id) DO UPDATE SET council_number=$4,council_state=$5,rqe=$6,public_booking_enabled=$7,updated_by=$8`,[request.auth.tenantId,input.professionalUserId,input.specialtyId,input.councilNumber||null,input.councilState||null,input.rqe||null,input.publicBookingEnabled,request.auth.userId]);await client.query(`INSERT INTO professional_services(tenant_id,professional_user_id,specialty_id,procedure_id,public_booking_enabled,created_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id,professional_user_id,specialty_id,procedure_id) DO UPDATE SET public_booking_enabled=$5`,[request.auth.tenantId,input.professionalUserId,input.specialtyId,input.procedureId,input.publicBookingEnabled,request.auth.userId]);return reply.code(201).send({saved:true});});});
  app.delete("/professional-services/:professionalUserId/:specialtyId/:procedureId",{preHandler:[requirePermission("tenant.manage")]},async(request,reply)=>{const input=professionalServiceParams.parse(request.params);return withTenant(request.auth,async client=>{const result=await client.query("DELETE FROM professional_services WHERE tenant_id=$1 AND professional_user_id=$2 AND specialty_id=$3 AND procedure_id=$4 RETURNING procedure_id",[request.auth.tenantId,input.professionalUserId,input.specialtyId,input.procedureId]);if(!result.rows[0])return reply.code(404).send({error:"professional_service_not_found"});return reply.code(204).send();});});
  app.get("/schedules",{preHandler:[requirePermission("appointments.read")]},async request=>withTenant(request.auth,async client=>({items:(await client.query(`SELECT s.id,s.professional_user_id,u.name AS professional_name,s.unit_id,cu.name AS unit_name,s.weekday,to_char(s.starts_at,'HH24:MI') AS starts_at,to_char(s.ends_at,'HH24:MI') AS ends_at,s.status FROM professional_schedules s JOIN users u ON u.id=s.professional_user_id JOIN clinic_units cu ON cu.tenant_id=s.tenant_id AND cu.id=s.unit_id WHERE s.tenant_id=$1 ORDER BY u.name,s.weekday,s.starts_at`,[request.auth.tenantId])).rows})));
  app.post("/schedules",{preHandler:[requirePermission("tenant.manage")]},async(request,reply)=>{const input=scheduleInput.parse(request.body);return withTenant(request.auth,async client=>{const valid=await client.query(`SELECT EXISTS(SELECT 1 FROM tenant_memberships WHERE tenant_id=$1 AND user_id=$2 AND status='active' AND role IN('owner','admin','clinician')) AS professional_ok,EXISTS(SELECT 1 FROM clinic_units WHERE tenant_id=$1 AND id=$3 AND status='active') AS unit_ok`,[request.auth.tenantId,input.professionalUserId,input.unitId]);if(!valid.rows[0]?.professional_ok||!valid.rows[0]?.unit_ok)return reply.code(400).send({error:"schedule_reference_invalid"});const result=await client.query<{id:string}>(`INSERT INTO professional_schedules(tenant_id,professional_user_id,unit_id,weekday,starts_at,ends_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id`,[request.auth.tenantId,input.professionalUserId,input.unitId,input.weekday,input.startsAt,input.endsAt,request.auth.userId]);return reply.code(201).send({id:result.rows[0]!.id});});});
  app.delete("/schedules/:id",{preHandler:[requirePermission("tenant.manage")]},async(request,reply)=>{const{id}=idParams.parse(request.params);return withTenant(request.auth,async client=>{const result=await client.query("DELETE FROM professional_schedules WHERE tenant_id=$1 AND id=$2 RETURNING id",[request.auth.tenantId,id]);if(!result.rows[0])return reply.code(404).send({error:"schedule_not_found"});return reply.code(204).send();});});
  app.get("/blocks",{preHandler:[requirePermission("appointments.read")]},async request=>withTenant(request.auth,async client=>({items:(await client.query(`SELECT b.id,b.professional_user_id,u.name AS professional_name,b.unit_id,cu.name AS unit_name,b.starts_at,b.ends_at,b.reason FROM schedule_blocks b JOIN users u ON u.id=b.professional_user_id LEFT JOIN clinic_units cu ON cu.tenant_id=b.tenant_id AND cu.id=b.unit_id WHERE b.tenant_id=$1 AND b.ends_at>=now()-interval '30 days' ORDER BY b.starts_at`,[request.auth.tenantId])).rows})));
  app.post("/blocks",{preHandler:[requirePermission("tenant.manage")]},async(request,reply)=>{const input=blockInput.parse(request.body);return withTenant(request.auth,async client=>{const result=await client.query<{id:string}>(`INSERT INTO schedule_blocks(tenant_id,professional_user_id,unit_id,starts_at,ends_at,reason,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id`,[request.auth.tenantId,input.professionalUserId,input.unitId||null,input.startsAt,input.endsAt,input.reason,request.auth.userId]);return reply.code(201).send({id:result.rows[0]!.id});});});
  app.delete("/blocks/:id",{preHandler:[requirePermission("tenant.manage")]},async(request,reply)=>{const{id}=idParams.parse(request.params);return withTenant(request.auth,async client=>{const result=await client.query("DELETE FROM schedule_blocks WHERE tenant_id=$1 AND id=$2 RETURNING id",[request.auth.tenantId,id]);if(!result.rows[0])return reply.code(404).send({error:"block_not_found"});return reply.code(204).send();});});
}
