import { z } from "zod";

const schema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  HOST: z.string().default("0.0.0.0"),
  PORT: z.coerce.number().int().min(1).max(65535).default(4000),
  DATABASE_URL: z.string().url(),
  WEB_ORIGIN: z.string().url(),
  COOKIE_SECRET: z.string().min(32),
  SESSION_PEPPER: z.string().min(32),
  SESSION_TTL_HOURS: z.coerce.number().int().min(1).max(168).default(12),
  WHO_ICD_CLIENT_ID: z.preprocess((value) => value === "" ? undefined : value, z.string().trim().min(1).optional()),
  WHO_ICD_CLIENT_SECRET: z.preprocess((value) => value === "" ? undefined : value, z.string().trim().min(1).optional()),
  WHO_ICD_RELEASE: z.string().trim().default("2026-01"),
  WHO_ICD_LANGUAGE: z.string().trim().default("pt"),
  BILLING_PROVIDER: z.enum(["manual", "asaas"]).default("manual"),
  ASAAS_ENVIRONMENT: z.enum(["sandbox", "production"]).default("sandbox"),
  ASAAS_API_KEY: z.preprocess((value) => value === "" ? undefined : value, z.string().trim().min(20).optional()),
  ASAAS_WEBHOOK_TOKEN: z.preprocess((value) => value === "" ? undefined : value, z.string().trim().min(32).optional()),
  PUBLIC_APP_URL: z.string().url().default("http://localhost:5173"),
  PUBLIC_API_URL: z.string().url().default("http://localhost:4000"),
  WHATSAPP_PROVIDER: z.enum(["sandbox", "meta"]).default("sandbox"),
  WHATSAPP_GRAPH_VERSION: z.string().regex(/^v\d+\.\d+$/).default("v23.0"),
  WHATSAPP_PHONE_NUMBER_ID: z.preprocess((value)=>value===""?undefined:value,z.string().trim().min(5).optional()),
  WHATSAPP_ACCESS_TOKEN: z.preprocess((value)=>value===""?undefined:value,z.string().trim().min(20).optional()),
  WHATSAPP_WEBHOOK_VERIFY_TOKEN: z.string().min(16).default("replace-with-a-random-webhook-token"),
  WHATSAPP_APP_SECRET: z.preprocess((value)=>value===""?undefined:value,z.string().trim().min(16).optional()),
  WHATSAPP_CONFIRMATION_TEMPLATE: z.string().trim().default("prontuvia_confirmacao_consulta"),
  WHATSAPP_REMINDER_TEMPLATE: z.string().trim().default("prontuvia_lembrete_consulta"),
  WHATSAPP_ACCESS_CODE_TEMPLATE: z.string().trim().default("prontuvia_codigo_acesso"),
  NOTIFICATION_WORKER_INTERVAL_SECONDS: z.coerce.number().int().min(15).max(3600).default(60),
  MEDPLUM_BASE_URL: z.string().url().default("http://localhost:8103/"),
  MEDPLUM_CLIENT_ID: z.preprocess((value) => value === "" ? undefined : value, z.string().trim().min(1).optional()),
  MEDPLUM_CLIENT_SECRET: z.preprocess((value) => value === "" ? undefined : value, z.string().trim().min(1).optional()),
  NFSE_PROVIDER: z.enum(["sandbox", "focusnfe", "enotas"]).default("sandbox"),
  NFSE_API_TOKEN: z.preprocess((value) => value === "" ? undefined : value, z.string().trim().min(10).optional()),
  BANK_RECONCILIATION_PROVIDER: z.enum(["ofx", "openfinance", "sandbox"]).default("ofx"),
  AI_PROVIDER: z.enum(["disabled", "local", "openai"]).default("disabled"),
  AI_API_KEY: z.preprocess((value) => value === "" ? undefined : value, z.string().trim().min(10).optional()),
});

export const config = schema.parse(process.env);
